### PR TITLE
Added java solution for 14, 55 / python solution for 2420

### PR DESCRIPTION
**Pull request by green-study**
Added number 14(Longest_Common_Prefix) for java
Added number 2420(Find All Good Indices) for python
Added number 55(Jump_Game) for java
If any formatting is to be done, kindly inform.

Thank you.

### CODE REVIEW

**Review by qiyuangong — APPROVED** [review]
LGTM

**Comment by qiyuangong** [comment]
Nice PR. :)

**Comment by qiyuangong** [comment]
The only suggestion is that when starting a new pull request. Please check out a new branch from latest main/master (need to fetch and rebase with upstream). That will make PR and message clean.

**Comment by LONGNEW** [comment]
> The only suggestion is that when starting a new pull request. Please check out a new branch from latest main/master (need to fetch and rebase with upstream). That will make PR and message clean.

@qiyuangong Thank you for the advice.

**Pull request merged**
